### ISSUE TITLE
Problematic sample

### ISSUE THREAD

**Issue by ChinmaySeth** [CMSMUSiC/NanoMUSiC#110]
WWTo2L2Nu_MLL_1800ToInf_13TeV_PH is a problematic sample because the cross section is too high.

[WWTo2L2Nu_MLL_1800ToInf_13TeV_PH]
XSec = 11.09 # this xSec is completely off !!!
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "NNLO"
ProcessGroup = "WW"

**Comment by ossobooker** [comment]
@ChinmaySeth , can you check this, please?!

**Comment by ftorrresd** [comment]
https://cms-pdmv-prod.web.cern.ch/grasp/samples?dataset_query=WWTo2L2Nu_MLL_1800ToInf_TuneCP5_13TeV-powheg-pythia8&campaign=Phase2Spring23*GS,Run3Summer22*GS,Run3Summer23*GS,Run3Winter22*GS,Run3Winter23*GS,Run3Winter24*GS,RunIISummer20UL16*GEN,RunIISummer20UL16*GENAPV,RunIISummer20UL17*GEN,RunIISummer20UL18*GEN

**Comment by ftorrresd** [comment]
https://cms-pdmv-prod.web.cern.ch/mcm/public/restapi/requests/get_test/EXO-RunIISummer20UL18pLHEGEN-00007

**Comment by ftorrresd** [comment]
will not be fixed for this publication
