### ISSUE TITLE
Replace GJet sample with ones without the DR0p4 cut

### ISSUE THREAD

**Issue by ChinmaySeth** [CMSMUSiC/NanoMUSiC#112]
Use these samples
https://cms-pdmv.cern.ch/grasp/samples?dataset_query=GJets_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8&campaign=Run3Summer22*GS,Run3Winter22*GS,Run3Winter23*GS,RunIISummer20UL16*GEN,RunIISummer20UL16*GENAPV,RunIISummer20UL17*GEN,RunIISummer20UL18*GEN&nanoaod_version=v9

**Comment by ChinmaySeth** [comment]
Added to the DAS Sample list

**Comment by ossobooker** [comment]
Done
